// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odawqbevdzpkwkxbggnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kYXdxYmV2ZHpwa3dreGJnZ25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODQ5MTIsImV4cCI6MjA3Mjg2MDkxMn0.zCWL3uBD6PMOJnBf3cm2AxoFzjsAMLKRKpfQ8lzlo0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});